config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	devise_scope :admins do
		get 'admins/sign_in' => 'admins/sessions#create'
		get 'admins/sign_out' => 'admins/sessions#destroy'
	end

	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}

	devise_scope :customers do
		get 'customers/sign_in' => 'customers/sessions#create'
		get 'customers/sign_out' => 'customers/sessions#destroy'
	end

	namespace :admins do
		resources :customers, only:[:index, :show, :edit, :update]
		resources :products
		resources :order_items, only: [:index, :show, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		root 'homes#top'
	end

	namespace :customers do
		resources :customers, only:[:show, :edit, :update]do
			member do
				get :delete, as: :delete
				patch :active_false, as: :active_false
			end
		resources :order_details, only:[:new, :index, :create, :update]do
			member do
				get :complete, as: :complete
			end
		end
		resources :order_items, only:[:index, :show]
		resources :carts, only:[:index, :update, :destroy, :create]
	    delete '/customers/customers/:customer_id/cart_alldestroy' => 'carts#alldestroy', as: :alldestroy
		resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
		end
		root 'homes#top'
	end

	resources :products, only: [:index, :show]do
		member do
			get :genre_search
		end
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :product
	belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	 devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :validatable

	 has_many :shipping_addresses
	 has_many :order_details
	 has_many :carts

	 validates :family_name, presence: true
	 validates :first_name, presence: true
	 validates :family_name_kana, presence: true
	 validates :first_name_kana, presence: true
	 validates :postal_code, presence: true
	 validates :address, presence: true
	 validates :telephone_number, presence: true
	 validates :email, presence: true

	def full_address
		self.full_address = postal_code + address + family_name + first_name
	end

	def full_name
		family_name + first_name
	end

	def active_for_authentication?
    	super && (self.is_acctive == true)
  	end

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :genre_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  has_many :order_items
  belongs_to :customer

  def total_number
    order_items.sum(:number)
  end


	enum order_status:{
    wait_deposit: 0, #入金待ち
    payment_confirmation: 1, #入金確認
    inproduction: 2, #制作中
    preparing_for_shipment: 3, #発送準備中
    sent: 4, #発送済み
  }

  enum payment_method:{
    bank_transfer: 0, #銀行振込
    credit: 1, #クレジット払い
  }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order_detail
	belongs_to :product

	enum creation_status:{cannot: 0, waiting: 1, doing: 2, done: 3}
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	belongs_to :genre
	has_many :order_items
	has_many :carts, dependent: :destroy

	validates :product_name, presence: true
	validates :unit_price, presence: true
	validates :product_description,length: {maximum: 50}


end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	validates :shipping_postal_code, presence: true
	validates :shipping_address, presence: true
	validates :shipping_name, presence: true

	def full_address
		shipping_postal_code + shipping_address + shipping_name
	end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins'

	def index
		@genre = Genre.new
		@genres = Genre.all.page(params[:page]).per(5)
	end

	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			redirect_to admins_genres_path
			flash[:notice] = "Genre was successfully created."
		else
			redirect_to admins_genres_path
			flash[:notice] = "Genre was not successfully created."
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
  		if @genre.update(genre_params)
  			redirect_to admins_genres_path
  			flash[:notice] = "Genre was successfully update."
  		else
  			render "edit"
  			flash[:notice] = "Genre was not successfully apdate."
  		end
	end

	private

	def genre_params
  		params.require(:genre).permit(:genre_name, :flag_active)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_root_path(resource)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:family_name, :first_name , :family_name_kana, :first_name_kana, :postal_code, :address,:telephone_number])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_customer!, only: [:show]
	layout 'customers'
	def index
		@genres = Genre.all
		@products = Product.all.page(params[:page]).reverse_order.per(8)
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart = Cart.new
		if @product.is_selling == false
			redirect_to products_path, alert:"選択した商品は売り切れです"
		end
	end

	def genre_search
		@genres = Genre.all
		@genre = Genre.find(params[:id])
		@products = Product.where(genre_id: params[:id])
	end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h1>ジャンル編集画面</h1>

      <!-- ジャンル編集フォーム -->
      <div class="create-genres">
        <%= form_for @genre, url: admins_genre_path do |f| %>
        <div class="form-inline">
          <div class="form-group">
            <%= f.label :genre_name, " ジャンル" %>
            <%= f.text_field :genre_name, :class => "form-control edit-form" %>&emsp;
          </div>

          <div class= "form-group">
            <%= f.radio_button :flag_active, :true %>
            <%= f.label :flag_active, "有効　" %>&emsp;
          </div>

          <div class= "form-group">
            <%= f.radio_button :flag_active, :false %>
            <%= f.label :flag_active, "無効　" %>&emsp;
          </div>
          <%= f.submit "変更を保存する", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8">
			<h1>ジャンル追加・一覧画面</h1>

			<!-- ジャンル作成フォーム -->
			<div class="create-genres">
				<%= form_for @genre, url: admins_genres_path do |f| %>
				<div class="form-inline">
					<div class="form-group">
						<%= f.label :genre_name, "ジャンル" %>
						<%= f.text_field :genre_name, :class => "form-control edit-form" %> &emsp;
					</div>

					<div class= "form-group">
						<%= f.radio_button :flag_active, :true %>
						<%= f.label :flag_active, "有効" %> &emsp;
					</div>

					<div class= "form-group">
						<%= f.radio_button :flag_active, :false %>
						<%= f.label :flag_active, "無効" %> &emsp;
					</div>

					<%= f.submit "追加", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>

			<br>

			<!-- ジャンル一覧表示 -->
			<div class = "genre-list">
				<table class="table">
					<thead>
						<tr>
							<th>ジャンル</th>
							<th>状態</th>
							<th colspan="3"></th>
						</tr>
					</thead>

					<tbody>
						<% @genres.each do |genre| %>
						<tr>
							<td><%= genre.genre_name%></td>
							<%if genre.flag_active == true %>
							<td>有効</td>
							<% else %>
							<td>無効</td>
							<% end %>
							<td><%= link_to "編集する", edit_admins_genre_path(genre.id), class: "btn btn-primary" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
				<div class="text-center"><%= paginate @genres %></div>
			</div>
		</div>
	</div>
</div>