config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	devise_scope :admins do
		get 'admins/sign_in' => 'admins/sessions#create'
		get 'admins/sign_out' => 'admins/sessions#destroy'
	end

	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}

	devise_scope :customers do
		get 'customers/sign_in' => 'customers/sessions#create'
		get 'customers/sign_out' => 'customers/sessions#destroy'
	end

	namespace :admins do
		resources :customers, only:[:index, :show, :edit, :update]
		resources :products
		resources :order_items, only: [:index, :show, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		root 'homes#top'
	end

	namespace :customers do
		resources :customers, only:[:show, :edit, :update]do
			member do
				get :delete, as: :delete
				patch :active_false, as: :active_false
			end
		resources :order_details, only:[:new, :index, :create, :update]do
			member do
				get :complete, as: :complete
			end
		end
		resources :order_items, only:[:index, :show]
		resources :carts, only:[:index, :update, :destroy, :create]
	    delete '/customers/customers/:customer_id/cart_alldestroy' => 'carts#alldestroy', as: :alldestroy
		resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
		end
		root 'homes#top'
	end

	resources :products, only: [:index, :show]do
		member do
			get :genre_search
		end
	end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	 devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :validatable

	 has_many :shipping_addresses
	 has_many :order_details
	 has_many :carts

	 validates :family_name, presence: true
	 validates :first_name, presence: true
	 validates :family_name_kana, presence: true
	 validates :first_name_kana, presence: true
	 validates :postal_code, presence: true
	 validates :address, presence: true
	 validates :telephone_number, presence: true
	 validates :email, presence: true

	def full_address
		self.full_address = postal_code + address + family_name + first_name
	end

	def full_name
		family_name + first_name
	end

	def active_for_authentication?
    	super && (self.is_acctive == true)
  	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order_detail
	belongs_to :product

	enum creation_status:{cannot: 0, waiting: 1, doing: 2, done: 3}
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins'
	def index
		@customers = Customer.all.page(params[:page]).per(10)
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
			redirect_to admins_customer_path(@customer.id)
		else
			render action: :edit
		end
	end
	private
	def customer_params
	    params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_acctive)
	end
end

app/controllers/admins/order_items_controller.rb
class Admins::OrderItemsController < ApplicationController
		layout 'admins'
	def index
		@order_details = OrderDetail.all.page(params[:page]).per(5)
	end
	def show
		@order_detail = OrderDetail.find(params[:id])
		@order_items = @order_detail.order_items
	end

	def update
		@order_item = OrderItem.find(params[:id])
		@order_detail = OrderDetail.find_by(id: @order_item.order_detail_id)
		@order_item.update(order_item_params)

		#@order_itemsの制作ステータスのカラムで配列を作り、その中から制作済み(done)を削除
		#配列の中身が空であれば全て商品の制作ステータスが制作済みということになるのでそのタイミングで注文ステータスを配送準備中に切り替える
		@order_items = @order_detail.order_items.map{ |h| h[:creation_status] }
		@order_items.delete("done")

		if @order_item.creation_status == "cannot"
			@order_detail.order_status = 1
		elsif @order_item.creation_status == "weit"
			@order_detail.order_status = 1
		elsif @order_item.creation_status == "doing"
			@order_detail.order_status = 2
		elsif @order_item.creation_status == "done"
			if @order_items.length == 0
				@order_detail.order_status = 3
			end
		end

		@order_detail.update(order_detail_params)
		redirect_back(fallback_location: admins_root_path)
 	end

 	private

 	def order_item_params
		params.require(:order_item).permit(:creation_status)
	end

	def order_detail_params
		params.permit(:order_status)
	end
end

app/controllers/customers/carts_controller.rb
class Customers::CartsController < ApplicationController
	layout 'customers'
	def create
		@cart = Cart.find_by(customer_id: current_customer.id, product_id: params[:cart][:product_id])
		# 同じ商品が入っている場合は追加しない
		if @cart.present?
			redirect_to customers_customer_carts_path(current_customer.id),alert:"選択した商品はすでにカートに入っています。"
		else
			@cart = Cart.new(cart_params)
			@cart.customer_id = current_customer.id
			@cart.save
			redirect_to customers_customer_carts_path(current_customer.id),notice:"商品をカートに追加しました。"
		end
	end

	def index
		@customer = current_customer
		@carts = current_customer.carts
		@cart = Cart.new
	end

	def update
		@customer = current_customer
		@cart = Cart.find_by(customer_id: @customer.id,id: params[:id])
		@cart.update(cart_params)
		redirect_to customers_customer_carts_path(current_customer.id)
	end

	def destroy
		@customer = current_customer
		@cart = Cart.find_by(customer_id: @customer.id,id: params[:id])
		@cart.destroy
		redirect_to customers_customer_carts_path(@customer.id)
	end

	def alldestroy
		@customer = current_customer
		@carts = current_customer.carts
		@carts.destroy_all
		redirect_to customers_customer_carts_path(@customer.id)
	end

	private
	def cart_params
		params.require(:cart).permit(:number,:product_id)
	end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
	before_action :authenticate_customer!
	layout 'customers'
	def show
	 @customer =Customer.find(params[:id])
	end

	def delete
	 @customer = Customer.find(params[:id])
	end

	def edit
	 @customer = Customer.find(params[:id])
	end

	def update
	 @customer = Customer.find(params[:id])
	 if @customer.update(customer_params)
	 	redirect_to customers_customer_path(@customer.id)
	 else
		render :edit
	 end
	end

	def active_false
		@customer = Customer.find(params[:id])
		@customer.is_acctive = false
		@customer.save
		reset_session
		redirect_to customers_root_path
	end



	private
	def customer_params
	    params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
	end
	end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
	layout 'customers'
	def top
		@genres = Genre.all
		@products = Product.all
	end
end

app/controllers/customers/order_details_controller.rb
class Customers::OrderDetailsController < ApplicationController
	layout 'customers'
	before_action :authenticate_customer!

	def new
		@customer = Customer.find(params[:customer_id])
		if @customer.carts.blank?
 			flash[:blank] = "カートの中身がありません"
			redirect_to customers_customer_carts_path(current_customer.id)
		else
			@order_detail = OrderDetail.new
		end
	end

	def index
		@carts = current_customer.carts
		@customer = current_customer
		@order_detail = OrderDetail.new(order_detail_params)

		if  params[:select_address] == "ご自身の住所"
			@order_detail.shipping_postal_code = current_customer.postal_code
      @order_detail.shipping_address = current_customer.address
      @order_detail.shipping_name = current_customer.family_name + current_customer.first_name

    elsif params[:select_address] == "登録済み住所から選択"
    	@shipping_address = ShippingAddress.find(params[:detail][:shipping_address_id])
    # 上記の偽装モデル(:detail)に(shipping_address_id)を格納する。後ほどコントローラで呼び出す。
			@order_detail.shipping_postal_code = @shipping_address.shipping_postal_code
			@order_detail.shipping_address = @shipping_address.shipping_address
			@order_detail.shipping_name = @shipping_address.shipping_name

		elsif params[:select_address] ==  "新しいお届け先"
			@shipping_address = ShippingAddress.new(shipping_address_params)
		#新しいお届け先を登録するためにnewする
			@shipping_address.customer_id = current_customer.id
			@shipping_address.save
			@order_detail.shipping_postal_code = @shipping_address.shipping_postal_code
			@order_detail.shipping_address = @shipping_address.shipping_address
			@order_detail.shipping_name = @shipping_address.shipping_name
		end
	end

	def create
		@order_detail = OrderDetail.new(order_detail_params)
		@customer = current_customer
		@order_detail.customer_id = current_customer.id
		@carts = current_customer.carts
	#商品金額の計算
		array = []
			@carts.each do |cart|
				array << cart.product.unit_price * cart.number
			end
		@order_detail.subtotal = array.sum * 1.1
		@order_detail.total_fee = @order_detail.subtotal + @order_detail.shipping_fee
		if @order_detail.save
	#カートの中身をOrderItemテーブルにeachで格納
			current_customer.carts.each do |cart|
				order_item = OrderItem.new(order_detail_id: @order_detail.id, product_id: cart.product_id, number:cart.number, purchase_price: cart.number * cart.product.unit_price)
				order_item.save
			end
			current_customer.carts.destroy_all
			redirect_to complete_customers_customer_order_detail_path(current_customer.id,@order_detail.id)
		else
	#注文情報（orderdetail）にvalidatesをかけてあるので未入力の場合、ここでredirectを実行
			flash[:information_check] = "未入力の情報があります"
			redirect_to new_customers_customer_order_detail_path(current_customer.id,@order_detail.id)
		end
	end

	def update
		@order_detail = OrderDetail.find(params[:id])
		@order_items = @order_detail.order_items
		@order_detail.update(order_detail_params)

		if @order_detail.order_status == "wait_deposit"
			@order_items.update_all(creation_status: 0)
		elsif @order_detail.order_status == "payment_confirmation"
			@order_items.update_all(creation_status: 1)
		elsif @order_detail.order_status == "inproduction"
			@order_items.update_all(creation_status: 2)
		elsif @order_detail.order_status == "preparing_for_shipment"
			@order_items.update_all(creation_status: 3)
		elsif @order_detail.order_status == "sent"
			@order_items.update_all(creation_status: 3)
		end

		redirect_back(fallback_location: admins_root_path)
	end

	def complete
	end

	private
	def order_detail_params
		params.require(:order_detail).permit(:shipping_postal_code,:shipping_name,:shipping_address,:shipping_fee,:subtotal,:total_fee,:payment_method,:order_status)
	end

	def shipping_address_params
		params.require(:shipping_address).permit(:shipping_address_id, :shipping_postal_code, :shipping_address, :shipping_name)
	end

	def order_item_params
		params.require(:order_item).permit(:product_id,:number,:purchase_price)
	end
end

app/controllers/customers/order_items_controller.rb
class Customers::OrderItemsController < ApplicationController
	layout 'customers'
	before_action :authenticate_customer!

  def index
   	@order_details = current_customer.order_details.order("id DESC").page(params[:page]).per(5)
  end

	def show
    @order_detail = OrderDetail.find(params[:id])
    @order_item = @order_detail.order_items
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  layout 'customers'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def after_sign_in_path_for(resource)
      customers_root_path
  end

  # GET /resource/edit
  def after_sign_out_path_for(resource)
      new_customer_session_path
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  layout 'customers'
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
    def after_sign_in_path_for(resource)
      customers_root_path
    end

  # DELETE /resource/sign_out
    def after_sign_out_path_for(resource)
      new_customer_session_path
    end

  protected

  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みユーザーです。"
        redirect_to new_customer_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/shipping_addresses_controller.rb
class Customers::ShippingAddressesController < ApplicationController
layout 'customers'

def index
	@shipping_addresses = current_customer.shipping_addresses
	@shipping_address = ShippingAddress.new
	@customer = current_customer
  
end

def new
end

def create
	@shipping_address = ShippingAddress.new(shipping_address_params)
  @shipping_address.customer_id = current_customer.id
  	if @shipping_address.save #入力されたデータをdbに保存する。
      redirect_back(fallback_location: customers_root_path)
  		#redirect_to customers_customer_shipping_addresses_path(@customer.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@shipping_addresses = ShippingAddress.all
      @customer = current_customer
  		render 'index'
  	end
end
def edit
    @shipping_address = ShippingAddress.find(params[:id])
    @customer = current_customer

end

def update
   shipping_address = ShippingAddress.find(params[:id])
   @customer = current_customer
   if shipping_address.update(shipping_address_params)
    redirect_to customers_customer_shipping_addresses_path
      #redirect_to customers_customer_shipping_addresses_path(@customer.id), notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @shipping_address = ShippingAddress.find(params[:id])
      @customer = current_customer
      render 'edit'
    end
end

def destroy
  @shipping_address = ShippingAddress.find(params[:id])
  @shipping_address.destroy
  redirect_to customers_customer_shipping_addresses_path
end

end

  private
  def shipping_address_params
      params.require(:shipping_address).permit(:shipping_addresses_id, :shipping_postal_code, :shipping_address, :shipping_name)
  end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  layout 'customers'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/customers/order_items/index.html.erb
<div class="container">
	<dev class="row">
		<div class="col-xs-10 col-xs-offset-1">
				<h2>注文履歴一覧</h2>
					<table class="table">
						<thead>
							<tr class="active">
								<th>注文日</th>
								<th>配送先</th>
								<th>注文商品</th>
								<th>支払金額</th>
								<th>ステータス</th>
								<th>注文詳細</th>
							</tr>
						</thead>
							<% @order_details.each do |order_detail| %>
							<tr>
								<td><%= order_detail.created_at.strftime('%Y/%m/%d') %></td>
								<td>
									<%= order_detail.shipping_postal_code %><br>
									<%= order_detail.shipping_address %><br>
									<%= order_detail.shipping_name %>
								</td>
								<td>
									<% order_detail.order_items.each do |order_product| %>
										<%= order_product.product.product_name %><br>
									<% end %>
								</td>
								<td><%= order_detail.total_fee.to_s(:delimited) %>円</td>
									<% case order_detail.order_status %>
										<% when 'wait_deposit' %>
											<td>入金待ち</td>
										<% when 'payment_confirmation' %> 
											<td>入金確認</td>
									 	<% when 'inproduction' %>
											<td>制作中</td>
									 	<% when 'preparing_for_shipment' %>
											<td>発送準備中</td>
									 	<% when 'sent' %>
											<td>発送済み</td>
									<% end %>
								<td>
								<%= link_to customers_customer_order_item_path(current_customer.id,order_detail.id), class: "btn btn-success" do %>
										表示する
								<% end %>
								</td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			<div class="text-center"><%= paginate @order_details %></div>
			</div>
		</div>
	</div>
</dev>
</div>

app/views/customers/order_items/show.html.erb
<div class="container">
  <div class="row">
    <h2>注文履歴詳細</h2>
    <div class = "col-xs-6">
      <table class="table table-bordered">
        <tr>
          <th class="active">注文日</th>
          <td><%= @order_detail.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class="active">配送先</th>
          <td>〒<%= @order_detail.shipping_postal_code %><br>
              <%= @order_detail.shipping_address %><br>
              <%= @order_detail.shipping_name %></td>
        </tr>

        <tr>
          <th class="active">支払い方法</th>
            <% case @order_detail.payment_method %>
              <% when 'bank_transfer' %>
                <td>銀行振込</td>
              <% when 'credit' %>
                <td>クレジット払い</td>
              <% end %>
        </tr>

        <tr>
          <th class="active">ステータス</th>
            <% case @order_detail.order_status %>
              <% when 'wait_deposit' %>
                <td>入金待ち</td>
              <% when 'payment_confirmation' %>
                <td>入金確認</td>
              <% when 'inproduction' %>
                <td>制作中</td>
              <% when 'preparing_for_shipment' %>
                <td>発送準備中</td>
              <% when 'sent' %>
                <td>発送済み</td>
            <% end %>
          </td>
      </tr>
     </table>
    </div>

    <div class = "col-xs-3">
        <table class="table table-bordered">
          <tr>
            <th class="active">商品合計</th>
            <td><%= @order_detail.subtotal.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="active">配送料</th>
            <td><%= @order_detail.shipping_fee %>円</td>
          </tr>
          <tr>
            <th class="active">ご請求額</th>
            <td><%= @order_detail.total_fee.to_s(:delimited) %>円</td>
          </tr>
         </table>
      </div>

    <div class="row">
      <div class = "col-xs-9">
        <table class="table table-bordered">
          <table class="table">
            <thead>
              <tr class="active">
                <th>商品</th>
                <th>単価</th>
                <th>個数</th>
                <th>小計</th>
              </tr>
            </thead>
             <% @order_detail.order_items.each do |order_product| %>
            <tbody>
              <tr>
                <td><%= order_product.product.product_name %></td>
                <td><% unit_price_with_tax = (order_product.product.unit_price * 1.1).floor %>
                    <%= unit_price_with_tax.to_s(:delimited) %>円</td>
                <td><%= order_product.number %></td>
                <td><% purchase_price_with_tax = (order_product.purchase_price * 1.1).floor %>
                    <%= purchase_price_with_tax.to_s(:delimited) %>円</td>
              </tr>
             <% end %>
             </tbody>
          </table>
    </div>
  </div>
</div>