config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	devise_scope :admins do
		get 'admins/sign_in' => 'admins/sessions#create'
		get 'admins/sign_out' => 'admins/sessions#destroy'
	end

	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}

	devise_scope :customers do
		get 'customers/sign_in' => 'customers/sessions#create'
		get 'customers/sign_out' => 'customers/sessions#destroy'
	end

	namespace :admins do
		resources :customers, only:[:index, :show, :edit, :update]
		resources :products
		resources :order_items, only: [:index, :show, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		root 'homes#top'
	end

	namespace :customers do
		resources :customers, only:[:show, :edit, :update]do
			member do
				get :delete, as: :delete
				patch :active_false, as: :active_false
			end
		resources :order_details, only:[:new, :index, :create, :update]do
			member do
				get :complete, as: :complete
			end
		end
		resources :order_items, only:[:index, :show]
		resources :carts, only:[:index, :update, :destroy, :create]
	    delete '/customers/customers/:customer_id/cart_alldestroy' => 'carts#alldestroy', as: :alldestroy
		resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
		end
		root 'homes#top'
	end

	resources :products, only: [:index, :show]do
		member do
			get :genre_search
		end
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :product
	belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	 devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :validatable

	 has_many :shipping_addresses
	 has_many :order_details
	 has_many :carts

	 validates :family_name, presence: true
	 validates :first_name, presence: true
	 validates :family_name_kana, presence: true
	 validates :first_name_kana, presence: true
	 validates :postal_code, presence: true
	 validates :address, presence: true
	 validates :telephone_number, presence: true
	 validates :email, presence: true

	def full_address
		self.full_address = postal_code + address + family_name + first_name
	end

	def full_name
		family_name + first_name
	end

	def active_for_authentication?
    	super && (self.is_acctive == true)
  	end

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :genre_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  has_many :order_items
  belongs_to :customer

  def total_number
    order_items.sum(:number)
  end


	enum order_status:{
    wait_deposit: 0, #入金待ち
    payment_confirmation: 1, #入金確認
    inproduction: 2, #制作中
    preparing_for_shipment: 3, #発送準備中
    sent: 4, #発送済み
  }

  enum payment_method:{
    bank_transfer: 0, #銀行振込
    credit: 1, #クレジット払い
  }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order_detail
	belongs_to :product

	enum creation_status:{cannot: 0, waiting: 1, doing: 2, done: 3}
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	belongs_to :genre
	has_many :order_items
	has_many :carts, dependent: :destroy

	validates :product_name, presence: true
	validates :unit_price, presence: true
	validates :product_description,length: {maximum: 50}


end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	validates :shipping_postal_code, presence: true
	validates :shipping_address, presence: true
	validates :shipping_name, presence: true

	def full_address
		shipping_postal_code + shipping_address + shipping_name
	end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
	before_action :authenticate_admin!
	layout 'admins'

	def index
		@products = Product.all.page(params[:page]).per(10)
	end

	def new
		@product = Product.new
		@genre = Genre.all
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to admins_products_path
		else
			render action: :new
		end
	end

	def show
		@product = Product.find(params[:id])
		@genre = @product.genre
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to admins_product_path(@product.id)
		else
			render action: :edit
		end
	end

	private
	def product_params
		params.require(:product).permit(:genre_id, :product_name, :product_image, :product_description, :unit_price, :is_selling)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_root_path(resource)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:family_name, :first_name , :family_name_kana, :first_name_kana, :postal_code, :address,:telephone_number])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_customer!, only: [:show]
	layout 'customers'
	def index
		@genres = Genre.all
		@products = Product.all.page(params[:page]).reverse_order.per(8)
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart = Cart.new
		if @product.is_selling == false
			redirect_to products_path, alert:"選択した商品は売り切れです"
		end
	end

	def genre_search
		@genres = Genre.all
		@genre = Genre.find(params[:id])
		@products = Product.where(genre_id: params[:id])
	end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/products/_genre_templete.html.erb
 <!-- ジャンル一覧 -->
		<div class="col-xs-3">
			<table class="table" id = none-border>
				<thead>
					<th>ジャンル検索</th>
				</thead>
				<% genres.each do |genre| %>
					<tr>
						<td><%= link_to genre.genre_name,genre_search_product_path(genre.id),:style=>"color:black;" %></td>
					</tr>
				<% end %>
			</table>
		</div>

app/views/products/genre_search.html.erb
<div class="container">
	<div class="row">
		<!-- ジャンル一覧 -->
		<%= render "genre_templete",genres: @genres %>
		<!-- 検索商品一覧 -->
		<div class="col-xs-9">
			<h1><%= @genre.genre_name %>一覧</h1>
			<% i = 0 %>
			<table class="table" id="none-border">
				<% @products.each do |product| %>
					<!-- 写真 -->
					<td>
						<%=link_to product_path(product.id), :style => "color:black;" do %>
							<%= attachment_image_tag product, :product_image, :size => '200x150', fallback: "no_image.png"%>
							<br>
							<!-- 商品名-->
							<%= product.product_name %>
								<% if product.is_selling == false %>
									&emsp;<span class="bg-danger">売り切れ</span>
							<% end %>
							<br>
							<!-- 価格-->
							¥<% price = product.unit_price * 1.1 %>
							<%= price.floor.to_s(:delimited) %>
						<% end %>
					</td>
					<!-- 4つ毎に改行 -->
					<% i = i + 1 %>
					<% if i % 4 == 0 %>
						<tr></tr>
					<% end %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
	<!-- ジャンル一覧 -->
		<%= render "genre_templete",genres: @genres %>
		<!-- 商品一覧 -->
		<div class="col-xs-9">
			<%= image_tag 'product_list.png', :size=> '520x150' %><br>
			<br>
			<% i = 0 %>
			<table class="table" id="none-border">
				<% @products.each do |product| %>
					<!-- 写真 -->
					<td>
						<%= link_to product_path(product.id), :style=>"color:black;",data: {:turbolinks => "false"}  do %>
							<%= attachment_image_tag product, :product_image, :size => '200x150', fallback: "no_image.png"%>
							<br>
							<!-- 商品名-->
							<%= product.product_name %>
							<br>
							<!-- 価格-->
							¥<% price = product.unit_price * 1.1 %>
							<%= price.floor.to_s(:delimited) %>
							<% if product.is_selling == false %>
								&emsp;<span class="bg-danger">売り切れ</span>
							<% end %>
						<% end %>
					</td>
					<!-- 4つ毎に改行 -->
					<% i = i + 1 %>
					<% if i % 4 == 0 %>
						<tr></tr>
					<% end %>
				<% end %>
			</table>
			<div class="text-center"><%= paginate @products %></div>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<!-- ジャンル一覧 -->
		<%= render "genre_templete",genres: @genres %>
		<!--商品写真 -->
		<div class="col-xs-4"><%= attachment_image_tag @product, :product_image, :size => '350x300', fallback: "no_image.png" %></div>
		<!-- 商品情報 -->
		<div class="col-xs-5">
			<table class="table" id = none-border>
				<tbody>
					<tr id="big-size">
						<td>
							<%= @product.product_name %>
						</td>
					</tr>
					<tr>
						<td>
							<%= @product.product_description %>
						</td>
					</tr>

					<tr id="big-size">
						<td>
							<% price = @product.unit_price * 1.1 %>
							¥<%= price.floor.to_s(:delimited) %>(税込)
						</td>
					</tr>
					<tr>
						<%= form_for [@customer, @cart],url:customers_customer_carts_path(current_customer.id) do |f| %>
							<td><%= f.select :number, [1,2,3,4,5,6,7,8,9,10] %></td>
							<td><%= f.hidden_field :product_id, :value => @product.id %></td>
							<td><%= f.submit "カートに入れる",class: "btn btn-primary" %></td>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>