config/routes.rb
Rails.application.routes.draw do

	devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}

	devise_scope :admins do
		get 'admins/sign_in' => 'admins/sessions#create'
		get 'admins/sign_out' => 'admins/sessions#destroy'
	end

	devise_for :customers, controllers: {
  	sessions:      'customers/sessions',
  	passwords:     'customers/passwords',
  	registrations: 'customers/registrations'
	}

	devise_scope :customers do
		get 'customers/sign_in' => 'customers/sessions#create'
		get 'customers/sign_out' => 'customers/sessions#destroy'
	end

	namespace :admins do
		resources :customers, only:[:index, :show, :edit, :update]
		resources :products
		resources :order_items, only: [:index, :show, :update]
		resources :genres, only: [:index, :create, :edit, :update]
		root 'homes#top'
	end

	namespace :customers do
		resources :customers, only:[:show, :edit, :update]do
			member do
				get :delete, as: :delete
				patch :active_false, as: :active_false
			end
		resources :order_details, only:[:new, :index, :create, :update]do
			member do
				get :complete, as: :complete
			end
		end
		resources :order_items, only:[:index, :show]
		resources :carts, only:[:index, :update, :destroy, :create]
	    delete '/customers/customers/:customer_id/cart_alldestroy' => 'carts#alldestroy', as: :alldestroy
		resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
		end
		root 'homes#top'
	end

	resources :products, only: [:index, :show]do
		member do
			get :genre_search
		end
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :product
	belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	 devise :database_authenticatable, :registerable,
	         :recoverable, :rememberable, :validatable

	 has_many :shipping_addresses
	 has_many :order_details
	 has_many :carts

	 validates :family_name, presence: true
	 validates :first_name, presence: true
	 validates :family_name_kana, presence: true
	 validates :first_name_kana, presence: true
	 validates :postal_code, presence: true
	 validates :address, presence: true
	 validates :telephone_number, presence: true
	 validates :email, presence: true

	def full_address
		self.full_address = postal_code + address + family_name + first_name
	end

	def full_name
		family_name + first_name
	end

	def active_for_authentication?
    	super && (self.is_acctive == true)
  	end

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :genre_name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  has_many :order_items
  belongs_to :customer

  def total_number
    order_items.sum(:number)
  end


	enum order_status:{
    wait_deposit: 0, #入金待ち
    payment_confirmation: 1, #入金確認
    inproduction: 2, #制作中
    preparing_for_shipment: 3, #発送準備中
    sent: 4, #発送済み
  }

  enum payment_method:{
    bank_transfer: 0, #銀行振込
    credit: 1, #クレジット払い
  }

  validates :payment_method, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order_detail
	belongs_to :product

	enum creation_status:{cannot: 0, waiting: 1, doing: 2, done: 3}
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	belongs_to :genre
	has_many :order_items
	has_many :carts, dependent: :destroy

	validates :product_name, presence: true
	validates :unit_price, presence: true
	validates :product_description,length: {maximum: 50}


end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :customer

	validates :shipping_postal_code, presence: true
	validates :shipping_address, presence: true
	validates :shipping_name, presence: true

	def full_address
		shipping_postal_code + shipping_address + shipping_name
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_customer!, only: [:show]
	layout 'customers'
	def index
		@genres = Genre.all
		@products = Product.all.page(params[:page]).reverse_order.per(8)
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart = Cart.new
		if @product.is_selling == false
			redirect_to products_path, alert:"選択した商品は売り切れです"
		end
	end

	def genre_search
		@genres = Genre.all
		@genre = Genre.find(params[:id])
		@products = Product.where(genre_id: params[:id])
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NaganoCakeShibuya</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<header class="navbar navbar-fixed-top">
		<div class="container">
			<nav class='nav navbar-nav navbar-left' >
				<%= image_tag('Nagano cake3.png') %>
			</nav>

			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if admin_signed_in? %>
						<li><%= link_to "商品一覧", admins_products_path,:style=>"color:white;" %></li>
						<li><%= link_to "会員一覧", admins_customers_path,:style=>"color:white;" %></li>
						<li><%= link_to "注文履歴一覧", admins_order_items_path,:style=>"color:white;" %></li>
						<li><%= link_to "ジャンル管理", admins_genres_path,:style=>"color:white;" %></li>
						<li><%= link_to "ログアウト", destroy_admin_session_path,:style=>"color:white;", method: :delete %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>
	<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaganoCakeShibuya</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/customers.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NaganoCakeShibuya</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<header class="navbar navbar-fixed-top">
		<div class="container">
			<nav class='nav navbar-nav navbar-left' >
				<%= link_to image_tag('Nagano cake3.png'),customers_root_path %>
			</nav>

			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if customer_signed_in? %>
						<li id = "welcome"><%="ようこそ#{current_customer.family_name}さん！"%></li>
						<li><%= link_to "マイページ", customers_customer_path(current_customer.id),:style=>"color:white;", class: 'glyphicon glyphicon-user'%></li>
						<li><%= link_to "商品一覧", products_path,:style=>"color:white;",class: "glyphicon glyphicon-gift" %></li>
						<li><%= link_to "カート", customers_customer_carts_path(current_customer.id),:style=>"color:white;",class: 'glyphicon glyphicon-shopping-cart' ,data: {:turbolinks => "false"} %></li>
						<li><%= link_to "ログアウト", destroy_customer_session_path,class: 'glyphicon glyphicon-log-out',:style=>"color:white;", method: :delete %></li>
					<% else %>
						<li><%= link_to "商品一覧", products_path,:style=>"color:white;",class: "glyphicon glyphicon-gift"  %></li>
						<li><%= link_to "新規登録", new_customer_registration_path,:style=>"color:white;",class: "glyphicon glyphicon-pencil"   %></li>
						<li><%= link_to "ログイン", new_customer_session_path,:style=>"color:white;",class: 'glyphicon glyphicon-log-in' %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>

	<% if flash[:notice] %>
  		<div class="alert alert-success">
    		<%= flash[:notice] %>
  		</div>
	<% end %>

	<% if flash[:alert] %>
  		<div class="alert alert-danger">
    		<%= flash[:alert] %>
  		</div>
	<% end %>

	<% if flash[:error] %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
  	<% end %>

	<%= yield %>
</body>
</html>